Repository readmeio/oas-extensions, pull requests merged in 2022-04, with the labels that each got.

#68 chore(deps-dev): bumping dev deps
  package-lock.json
  package.json
Labels: dependencies

#69 chore: docs cleanup
  .alexignore
  .alexrc
  .eslintignore
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  package-lock.json
  package.json
Labels: documentation

#70 ci: moving tests over to mocha, fixing node 18 compat issues
  .github/workflows/ci.yml
  .mocharc.json
  __tests__/.eslintrc
  __tests__/index.test.ts
  jest.config.js
  package-lock.json
  package.json
  test/.eslintrc
  test/helpers/init.js
  test/index.test.ts
  test/tsconfig.json
  tsconfig.test.json
Labels: enhancement
